name = "config-manager-backend"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "config-manager"
database_id = "76b9d4ce-67ca-49c8-b9d4-31a5f94a2ee0"
migrations_dir = "migrations"
